### ISSUE TITLE
Missed utils folders

### ISSUE THREAD

**Issue by taeyeopl** [jcorsetti/oryon.github.io#2]
Hi @jcorsetti, Thanks for sharing the codes. It looks like you have missed uploading the utils folders.

**Comment by jcorsetti** [comment]
Hi Taeyeop, indeed you are right, I just added them along with some missing scripts.
I will keep the issue open for a few days in case other files are missing.

**Comment by taeyeopl** [comment]
Thanks for the quick reply with updating.

**Comment by taeyeopl** [comment]
Do you have any plans for releasing the checkpoints to reproduce the report results? (e.g. exp_data/baseline/ files)

**Comment by jcorsetti** [comment]
The best checkpoint has been released along with the main code, is the oryon_best.zip file in the latest release. It can be evaluated as detailed in the example in the README

**Comment by taeyeopl** [comment]
`python run_train.py exp_name=baseline`
Run the following to obtain results with the basic four configurations. The last checkpoint is used by default.
`python run_test.py -cp exp_data/baseline/ dataset.test.name=nocs test.mask=predicted`


As far as I understand, the README suggests using the last checkpoint after training. what does it mean release the best checkpoint? Does the best checkpoint denotes `pretrained_models.zip` folders?

**Comment by taeyeopl** [comment]
https://github.com/jcorsetti/oryon/releases/download/v1.0.0-data/oryon_best.zip
I understood what you said. Thanks :)

**Comment by jcorsetti** [comment]
Sorry for the late reply.
The pretrained_models folder is used to store the checkpoints of third-party models we need, such as PointDSC.
The best checkpoint is the one released (oryon_best.zip), in order to evaluate it it should be unzipped in exp_data, and the run_test.py script should be run, using -cp exp_data/oryon_best as argument.

Let me know if something is unclear

**Comment by ismael-esp** [comment]
hi, @jcorsetti. first of all, thanks for sharing your code.

I encountered an error when trying to execute the run test Python file for either real275 or toyl. The error is the following.

FileNotFoundError: [Errno 2] No such file or directory: 'exp_data/oryon_final/results/toyl_cross_scene_test_all_19042024_2039_431.csv'

As highlighted before, I downloaded the oryon_best.zip file and extracted it into the exp_data folder. However, it appears that it doesn't include a results folder. Should I run another Python code to generate them, or am I doing something wrong?
Thanks in advance for your help.

**Comment by jcorsetti** [comment]
Hi @ismael-esp, thanks for your interest.
Yes, the code expects a "result" folder inside the oryon_final folder, as all the result files for the evaluation will be placed there.
For now you can create the results folder manually in exp_data/oryon_final and it should work. I will update the code so that it automatically creates the folder when needed.
Let me know if this solution does not work.
