### ISSUE TITLE
Question abot inference time

### ISSUE THREAD

**Issue by ran894694447** [jcorsetti/oryon.github.io#7]
Thanks for your great work! Can you tell me about the inference speed of this model? How many images can it process per second? I'm looking foward to your early reply!

**Comment by jcorsetti** [comment]
Hi, in the supplementary material we reported the inference time. A complete inference on one dataset (2000 image pairs) takes about one hour on an Nvidia V100, so that's about 1.1 image per second, considering 4000 images in 3600 seconds. 
This as an upper bound, as it also includes the I/O time, the metric computation and saving the results on disk.

**Comment by ran894694447** [comment]
Thank you for your reply!
